### ISSUE TITLE
Suggestion command

### ISSUE THREAD

**Issue by TimmyTradeMark** [DooJayu/RIRY#8]
Hello Kacper, can you make a command where people would make a suggestion and then the command of whatever suggestion the user put gets embedded into a assigned channel where people can upvote or downvote?

ex. !feedback or !suggestion [Insert problem here]
The suggested and feedback message gets converted into a embed message that would be sent to a assigned channel like #feedback-logs or #suggestion-logs

**Comment by DooJayu** [comment]
This is unnecessary since users can put up features + issues on this Github repo
